version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # تخزين الموديلات علشان متضيعش لو الكونتينر اتمسح
    command: >
      sh -c "ollama serve & sleep 5 && ollama pull mistral && wait"

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "3030:3030"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/chat

volumes:
  ollama_data:
