version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - coolify
    command: serve

  fastapi:
    build: .
    container_name: fastapi
    depends_on:
      - ollama
    ports:
      - "3030:3030"
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/chat
    networks:
      - coolify

networks:
  coolify:
    external: true
