version: "3.9"

networks:
  appnet:

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - appnet
    volumes:
      - ollama_data:/root/.ollama
    command: >
      sh -c "ollama serve & sleep 5 && ollama pull mistral && wait"

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "3030:3030"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/chat
    networks:
      - appnet

volumes:
  ollama_data:
